### ISSUE TITLE
JSON response not found

### ISSUE THREAD

**Issue by xabies** [Chiru/FIWARE-POIDataProvider#2]
Hi. I'm a newbie developer.

I have follow this tutorial with out problems: 
http://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/POI_Data_Provider_-_Installation_and_Administration_Guide
 But when I try to test the result:

http://127.0.0.1/poi_dp/radial_search.php?lat=1&lon=1&category=test_poi

I have nor result.

I have tried with:
http://127.0.0.1/poi_dp/radial_search.php
And the result is:
'lat' and 'lon' parameters must be specified!
so the scrip is called.

What could be the problem?

**Comment by nayecases** [comment]
@xabies You must specify the latitude and longitude parameters in order to use radial search

 But I have the same problem. I've installed everything following the POI installation guide and I get nothing executing the test at the end of the installation. Looking into the server log, I get the following error every time that I try to execute anything that is related to data (/radial_search, /bbox_search,/get_pois, etc):

```
PHP Fatal error:  Uncaught exception 'JsonSchema\\Exception\\JsonDecodingException' with message 'The maximum stack depth has been exceeded' in /var/www/poi_dp/vendor/justinrainbow
/json-schema/src/JsonSchema/RefResolver.php:107\nStack trace:\n#0 /var/www/poi_dp/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php(200): JsonSchema\\RefResolver->resolve(false, 'file:///var/www...')\n#1
 /var/www/poi_dp/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php(130): JsonSchema\\RefResolver->resolveProperty(Object(stdClass), 'additionalPrope...', 'file:///var/www...')\n#2
 /var/www/poi_dp/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php(200): JsonSchema\\RefResolver->resolve(Object(stdClass), 'file:///var/www...')\n#3
/var/www/poi_dp/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php(130): JsonSchema\\RefResolver->resolveProperty(Object(stdClass), 'items', 'file:///var/www...')\n#4 
/var/www/poi_dp/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php(182): JsonSchema\\RefResolver->resolve(Ob in /var/www/poi_dp/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php on line 107
```

First I changed the maximum json depth but it appears that it is stuck in an infinite loop and never finds the end of the JSON data. I've checked the json-schema library independently, and it works correctly. I've also checked database enconding. I think the problem resides with the data that is handed to json-schema but I've been unable to find what is exactly happening. 

Any idea where should I keep looking?

**Comment by ariokkon** [comment]
It seems that we have to get rid of that justinrainbow schema checker. It has apparently been changed so that it is not capable to handle recursive schemas.

**Comment by nayecases** [comment]
Thank you for looking into this, how should we proceed now? If it's possible, I would be very grateful if you could give us an estimated solution date.

Thanks in advance.

**Comment by nayecases** [comment]
Hello again, sorry for disturbing you once more. 

I was wondering if you had any advice at all, or a possible date when this issue can be resolved? Excuse us for insisting, but the POI Data Provider is a key module in our architecture and we need to know this so that we can reschedule our development process.  Thanks again.

**Comment by ariokkon** [comment]
There has been a problem with new justinrainbow/json-schema versions. You may try to define the version to be exactly 1.4.3 .
So, either try to correct your nonoperational installation or install from scratch

## Correcting the current installation
1. Delete the `vendor` subdirectory from your POI server
2. Install the version 1.4.3 of the justinrainbow/json-schema
   
   ```
   $ wget http://getcomposer.org/composer.phar
   $ php composer.phar require justinrainbow/json-schema:1.4.3
   $ sudo cp -r vendor /var/www/poi_dp/
   ```

(Anyway, arrange that new `vendor` subdirectory to the place where you deleted the previous one.)

## Installing from scratch

Use the installation guide at http://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/POI_Data_Provider_-_Installation_and_Administration_Guide . It is corrected to use the exact JSON validator version.

**Comment by nayecases** [comment]
Thank you very much, I'll do as you suggest.

**Comment by ariokkon** [comment]
Apparently Ok now.
